language: scala

env:
  - TRAVIS_JDK=11

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

jobs:
  include:
    - stage: validations
      script: scripts/validate-code.sh
      name: "Code validations (scalafmt, mima)"
   
    - stage: test-jdk11
      name: "Run tests with Scala 2.12 and AdoptOpenJDK 11" 
      script: scripts/test-code.sh
      env:
        - TRAVIS_SCALA_VERSION=2.12.11 
        - TRAVIS_JDK=11

    - name: "Run tests with Scala 2.13 and AdoptOpenJDK 11" 
      script: scripts/test-code.sh
      env: 
        - TRAVIS_SCALA_VERSION=2.13.1 
        - TRAVIS_JDK=11 
      
    - stage: test-jdk8
      name: "Run tests with Scala 2.12 and AdoptOpenJDK 8" 
      script: scripts/test-code.sh
      env: 
        - TRAVIS_SCALA_VERSION=2.12.11 
        - TRAVIS_JDK=8  

    - name: "Run tests with Scala 2.13 and AdoptOpenJDK 8" 
      script: scripts/test-code.sh
      env: 
        - TRAVIS_SCALA_VERSION=2.13.1 
        - TRAVIS_JDK=8  
        

    - stage: docs  
      script: scripts/validate-docs.sh
      name: "Validate documentation"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.sbt
    - $HOME/.coursier/cache

before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/play-slick*
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
